### ISSUE TITLE
Things have been deprecated in Qt 6

### ISSUE THREAD

**Issue by ratijas** [woboq/qmetaobject-rs#186]
This is a tracking issue for an upgrade process ongoing to adapt wrappers to major changes in Qt 6.

Some functionality have been completely removed in Qt 6, while others were only deprecated for the time being. One such class is `QMouseEvent` which is now full of deprecated methods. What's worse, they are not actually rendered as deprecated in official documentation ([QTBUG-95310](https://bugreports.qt.io/browse/QTBUG-95310)).

So, currently our Qt 6 builds are flashing with warnings coming from C++ compiler.

The task is to
1. forward those deprecation warnings to Rust using `#[deprecated]` attribute in tandem with some sort of `#[cfg_if(qt_6_0)]` versioning;
2. modify wrappers such that they don't produce warnings just because we merely compile them as part of out wrappers framework; i.e. don't shoot the messenger — only blame users who actually use those methods.
3. Fix things that should actually be fixed (upgraded) on qmetaobject-rs side.

List of warnings:

- [ ] «QMetaType::MovableType» => RelocatableType
  * [src/qmetatype.rs:203:98](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L203)
  * [src/qmetatype.rs:203:98](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L203)
- [ ] «static int QMetaType::type(const char*)»
  * [src/qmetatype.rs:288:44](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L288)
- [ ] «static const char* QMetaType::typeName(int)»
  * [src/qmetatype.rs:291:42](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L291)
  * [src/qmetatype.rs:291:50](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L291)
  * [src/qmetatype.rs:291:67](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L291)
  * [src/qmetatype.rs:291:75](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L291)
- [ ] «bool QVariant::canConvert(int) const»
  * [src/qmetatype.rs:393:39](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L393)
- [ ] «bool QVariant::convert(int)»
  * [src/qmetatype.rs:393:63](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L393)
- [ ] «QPointF QMouseEvent::localPos() const»
  * [src/qtdeclarative.rs:885:34](https://github.com/woboq/qmetaobject-rs/blob/b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7/qmetaobject/src/qmetatype.rs#L885)

All links are hard-wired to commit b81438cbf56acb0bb8d6a17aa5299bdcae87a2e7 to avoid ambiguity. Use git blame to locate them within latest changes.

Also,
- [ ] make a tutorial for qmetaobject-rs developers on how to deal with deprecated functionality while still keeping backward compatibility with Qt 5 and earlier versions of Qt 6.

**Comment by ratijas** [comment]
By the way, aforementioned QTBUG-95310 was marked as a duplicate of [QTBUG-94521](https://bugreports.qt.io/browse/QTBUG-94521) which they fixed just about last week.

**Comment by ratijas** [comment]
I see so many ways to deprecate stuff in C/C++, but none of them seem to have a reverse counterpart — the one to ignore warnings; or at least, to do it 

- https://clang.llvm.org/docs/AttributeReference.html#availability
- https://docs.microsoft.com/en-us/cpp/cpp/deprecated-cpp?view=msvc-160
- https://stackoverflow.com/questions/295120/c-mark-as-deprecated

So, I guess the only option is to disable warnings by their respective numbers on a per compiler basis.
